version: '3.4'

services:
  testedocker:
    container_name: 'dotnetapp'
    image: ${DOCKER_REGISTRY-}testedocker
    build:
      context: .
      dockerfile: TesteDocker/Dockerfile
    networks:
        - TesteNetwork
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5673:5672
        - 15673:15672
    volumes:
        - ./docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ./docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - TesteNetwork
  redis:
    image: redis
    container_name: 'redis'
    command: redis-server
    ports: 
        - 6379:6379
    volumes:
        - ./docker-conf/redis/data:/data
    networks:
        - TesteNetwork
networks:
    TesteNetwork:
        driver: bridge